<h1 style="font-family:Comic Sans MS;color:darkblue;">csgo_round_snapshots</h1>
<p>The csgo_round_snapshots.csv file typically contains data related to Counter-Strike:
    Global Offensive (CS:GO) match rounds and snapshots. </p>

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
data = pd.read_csv(r"E:\Projects Datas\csgo_round\csgo_round_snapshots.csv")
data.head()

time_left  ct_score  t_score       map  bomb_planted  ct_health  t_health  \
0     175.00       0.0      0.0  de_dust2         False      500.0     500.0   
1     156.03       0.0      0.0  de_dust2         False      500.0     500.0   
2      96.03       0.0      0.0  de_dust2         False      391.0     400.0   
3      76.03       0.0      0.0  de_dust2         False      391.0     400.0   
4     174.97       1.0      0.0  de_dust2         False      500.0     500.0   

   ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0       0.0      0.0    4000.0  ...                  0.0   
1     400.0    300.0     600.0  ...                  0.0   
2     294.0    200.0     750.0  ...                  0.0   
3     294.0    200.0     750.0  ...                  0.0   
4     192.0      0.0   18350.0  ...                  0.0   

   ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                      0.0                     0.0   
1                      0.0                     2.0   
2                      0.0                     2.0   
3                      0.0                     0.0   
4                      0.0                     0.0   

   ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                           0.0                          0.0   
1                           0.0                          0.0   
2                           0.0                          0.0   
3                           0.0                          0.0   
4                           0.0                          0.0   

   ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

   ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner  
0                      0.0                     0.0            CT  
1                      0.0                     0.0            CT  
2                      0.0                     0.0            CT  
3                      0.0                     0.0            CT  
4                      0.0                     0.0            CT  

[5 rows x 97 columns]

In [34]:
data.columns

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev',

In [35]:
data.shape

(122410, 97)

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object 
 4   bomb_planted                  122410 non-null  bool   
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-nul

In [37]:
data.isnull().sum().sum()

0

In [38]:
data.map.value_counts()

de_inferno     23811
de_dust2       22144
de_nuke        19025
de_mirage      18576
de_overpass    14081
de_train       13491
de_vertigo     11137
de_cache         145
Name: map, dtype: int64

In [39]:
data.bomb_planted.value_counts()

False    108726
True      13684
Name: bomb_planted, dtype: int64

In [40]:
data.round_winner.value_counts()

T     62406
CT    60004
Name: round_winner, dtype: int64

In [41]:
# Converting categorical features into a integer column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["bomb_planted"]=le.fit_transform(data["bomb_planted"])
data["map"]=le.fit_transform(data["map"])
data["round_winner"]=le.fit_transform(data["round_winner"])

In [42]:
data[['map','bomb_planted','round_winner']].dtypes

map             int32
bomb_planted    int64
round_winner    int32
dtype: object

In [50]:
abs(data.corr()['round_winner']).sort_values(ascending = False).head(25)

round_winner                    1.000000
ct_armor                        0.336382
ct_helmets                      0.308255
t_helmets                       0.297458
ct_defuse_kits                  0.291557
t_armor                         0.290753
ct_grenade_flashbang            0.253868
ct_players_alive                0.216798
ct_grenade_smokegrenade         0.209975
ct_weapon_awp                   0.198626
t_weapon_ak47                   0.194147
ct_health                       0.190662
bomb_planted                    0.187101
ct_weapon_m4a4                  0.178008
ct_grenade_hegrenade            0.168781
ct_grenade_incendiarygrenade    0.168517
ct_weapon_ak47                  0.166855
t_grenade_flashbang             0.166839
ct_weapon_sg553                 0.163963
t_weapon_sg553                  0.163709
ct_weapon_usps                  0.152893
t_weapon_awp                    0.149878
t_players_alive                 0.142518
t_grenade_smokegrenade          0.140348
t_weapon_usps   

In [52]:
X=data.drop(columns=["round_winner"])
y=data[["round_winner"]]

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=15)

In [54]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [57]:
#LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda=LinearDiscriminantAnalysis()

In [58]:
y.value_counts()

round_winner
1               62406
0               60004
dtype: int64

In [59]:
lda.fit(x_train,y_train)

C:\Users\Nithin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearDiscriminantAnalysis()

In [60]:
lda.transform(x_test)

array([[ 2.95107273],
       [ 0.52567688],
       [-1.24955806],
       ...,
       [ 2.42090756],
       [-1.24823798],
       [ 4.09085247]])

In [66]:
lda.coef_

array([[ 1.40136810e-01, -1.86393707e-02,  1.19354929e-02,
        -7.94487079e-02,  2.43136870e-01, -4.64030697e-01,
         3.52130082e-01, -5.46946431e-01,  5.27514331e-01,
        -2.05115222e-01,  1.60506168e-01,  2.76832319e-02,
         1.67043095e-01, -1.57503927e-02, -2.09802770e-01,
         3.08444311e-01, -1.98620507e-01,  6.03997297e-01,
        -2.07436335e-01,  2.70883607e-02, -3.17099313e-01,
         2.43132697e-01, -1.19423645e-16, -1.02722120e-02,
         2.50944937e-02,  1.63461764e-02, -1.47432462e-02,
         1.30553716e-02, -1.44560288e-01,  4.48140991e-02,
        -4.56798211e-16,  1.97231198e-02, -4.80649952e-02,
         1.33213973e-01,  2.40290459e-02, -1.07482214e-01,
         1.08696865e-02,  6.98453695e-17, -1.03707330e-01,
         4.12870161e-02, -4.82370138e-01,  9.85652721e-02,
        -2.25909379e-02,  1.06626547e-01, -1.64848682e-02,
         4.92028314e-03, -1.58282433e-02,  3.79867884e-02,
         9.12927794e-03, -5.53332586e-03, -1.17049081e-0

In [73]:
lda_coefficients=np.exp(np.abs(lda.coef_))

In [74]:
lda_coefficients= lda_coefficients.flatten()
lda_coefficients

array([1.15043118, 1.01881417, 1.01200701, 1.08269002, 1.27524316,
       1.59047179, 1.4220935 , 1.72796848, 1.69471457, 1.22766651,
       1.17410501, 1.02806997, 1.18180519, 1.01587508, 1.23343477,
       1.3613057 , 1.219719  , 1.82941693, 1.23051937, 1.02745859,
       1.37313894, 1.27523783, 1.        , 1.01032515, 1.02541201,
       1.01648051, 1.01485246, 1.01314097, 1.15553136, 1.04583342,
       1.        , 1.01991891, 1.04923885, 1.14249443, 1.02432007,
       1.11347106, 1.01092898, 1.        , 1.10927576, 1.04215118,
       1.61990926, 1.10358644, 1.02284805, 1.1125187 , 1.01662149,
       1.00493241, 1.01595417, 1.03871751, 1.00917108, 1.00554866,
       1.1241746 , 1.03341754, 1.        , 1.00752452, 1.0191277 ,
       1.01007151, 1.02755   , 1.01236905, 1.        , 1.00637736,
       1.        , 1.01606371, 1.00210565, 1.        , 1.25022659,
       1.72215797, 1.08821259, 1.02009522, 1.04971325, 1.08298081,
       1.02372303, 1.00225393, 1.03531169, 1.01819837, 1.04895

In [78]:
lda_coefficients.shape[0],(X.shape[1])

(96, 96)

In [79]:
feature_names=list(X.columns)

In [80]:
data_feature_score=pd.DataFrame({"Feature_names":feature_names,"feature_scores":lda_coefficients})
data_feature_score

Feature_names  feature_scores
0                     time_left        1.150431
1                      ct_score        1.018814
2                       t_score        1.012007
3                           map        1.082690
4                  bomb_planted        1.275243
..                          ...             ...
91  t_grenade_incendiarygrenade        1.009548
92    ct_grenade_molotovgrenade        1.009313
93     t_grenade_molotovgrenade        1.118288
94      ct_grenade_decoygrenade        1.002157
95       t_grenade_decoygrenade        1.029822

[96 rows x 2 columns]

In [82]:
top_20_values=data_feature_score.nlargest(20,'feature_scores')
top_20_values

Feature_names  feature_scores
17           t_weapon_ak47        1.829417
7                 ct_armor        1.727968
65          t_weapon_sg553        1.722158
8                  t_armor        1.694715
40          ct_weapon_m4a4        1.619909
5                ct_health        1.590472
6                 t_health        1.422093
20           ct_weapon_awp        1.373139
15         t_players_alive        1.361306
4             bomb_planted        1.275243
21            t_weapon_awp        1.275238
89  t_grenade_smokegrenade        1.268305
64         ct_weapon_sg553        1.250227
14        ct_players_alive        1.233435
18           ct_weapon_aug        1.230519
9                 ct_money        1.227667
16          ct_weapon_ak47        1.219719
87     t_grenade_flashbang        1.207722
12               t_helmets        1.181805
76          ct_weapon_usps        1.178931

In [83]:
top_20_values.index

Int64Index([17, 7, 65, 8, 40, 5, 6, 20, 15, 4, 21, 89, 64, 14, 18, 9, 16, 87,
            12, 76],
           dtype='int64')

In [84]:
x_train = x_train[:,[17, 7, 65, 8, 40, 5, 6, 20, 15, 4, 21, 89, 64, 14, 18, 9, 16, 87,
            12, 76]]

In [87]:
x_test = x_test[:,[17, 7, 65, 8, 40, 5, 6, 20, 15, 4, 21, 89, 64, 14, 18, 9, 16, 87,
            12, 76]]

In [91]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [92]:
models=[]
models.append(('lr',LogisticRegression(multi_class='ovr')))
models.append(('CART',DecisionTreeClassifier()))
models.append(('RFCA',RandomForestClassifier()))
models.append(('LDA',LinearDiscriminantAnalysis()))
models.append(('KNN',KNeighborsClassifier()))

In [95]:
import warnings
warnings.filterwarnings("ignore")

In [96]:
from sklearn import model_selection
names=[]
results=[]
for name, model in models:
    Kfold=model_selection.KFold(n_splits=10,random_state=15,shuffle=True)
    cv_results=model_selection.cross_val_score(model, x_train, y_train, cv=Kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    print(f"{name}: {cv_results.mean()} , {cv_results.std()}")

lr: 0.7492851839032015 , 0.005015074189317047
CART: 0.795094355945857 , 0.0030607210320509463
RFCA: 0.8410260196525596 , 0.0036638866361384816
LDA: 0.7481721210344991 , 0.005406821200498
KNN: 0.7791030447501852 , 0.0033887201209994947


In [97]:
model1 = RandomForestClassifier(n_estimators=500).fit(x_train,y_train)
y_pred1 = model1.predict(x_test)

In [99]:
from sklearn.metrics import confusion_matrix,classification_report

In [100]:
cm1 =confusion_matrix(y_test,y_pred1)
print(f"confusion_matrix RandomForest: \n {cm1} \n ")
print(f" report RandomForest: \n {classification_report(y_test,y_pred1)}")

confusion_matrix RandomForest: 
 [[10216  1657]
 [ 2023 10586]] 
 
 report RandomForest: 
               precision    recall  f1-score   support

           0       0.83      0.86      0.85     11873
           1       0.86      0.84      0.85     12609

    accuracy                           0.85     24482
   macro avg       0.85      0.85      0.85     24482
weighted avg       0.85      0.85      0.85     24482

